/** Original procedural artwork; generated by scripts/generate-editorial-art.py. */
import type { ImageSourcePropType } from 'react-native';
import type { VisibleTheme } from '../product/preferences';
const artwork: Record<VisibleTheme,{ landscape:ImageSourcePropType;book:ImageSourcePropType }> = {
 coral:{landscape:require('../../assets/editorial/landscape-coral.png'),book:require('../../assets/editorial/book-coral.png')},
 natural:{landscape:require('../../assets/editorial/landscape-natural.png'),book:require('../../assets/editorial/book-natural.png')},
 marine:{landscape:require('../../assets/editorial/landscape-marine.png'),book:require('../../assets/editorial/book-marine.png')},
};
export const editorialArt=(theme:VisibleTheme)=>artwork[theme];
