/** Guía pastoral: synthesis ORIGINAL, never endorsements by referenced organizations.
 * Each link identifies the SECTION supported; citations are metadata only, no source material copied.
 */
export type ReuseBasis='ORIGINAL_SINTESIS'|'CC'|'PUBLIC_DOMAIN'|'PERMISSION'|'SHORT_QUOTE_EXCEPTION'|'RESTRICTED';
export type PastoralSource={sourceTitle:string;sourceAuthorOrOrg:string;sourceUrl:string;sourceDateOrVersion:string;applicableSection:string;reuseBasis:ReuseBasis;checkedAt:string};
export type PastoralTopic={id:string;title:string;purpose:string;ages:string;group:string;adults:string;roles:string;materials:string;steps:readonly string[];adaptation:string;facilitation:string;prayer:string;christ:string;biblical:{book:string;chapter:number;start:number;end:number;reason:string};safeguarding:string;sources:readonly PastoralSource[]};
const checkedAt='2026-10-10';
const sources={
 youth:{sourceTitle:'Renewing the Vision: A Framework for Catholic Youth Ministry',sourceAuthorOrOrg:'United States Conference of Catholic Bishops (USCCB)',sourceUrl:'https://www.usccb.org/topics/youth-and-young-adult-ministries/renewing-vision',sourceDateOrVersion:'Junio de 1997',applicableSection:'orientación y liderazgo juvenil',reuseBasis:'ORIGINAL_SINTESIS' as const,checkedAt},
 participation:{sourceTitle:'Adolescent Kit training package for programme leaders',sourceAuthorOrOrg:'UNICEF',sourceUrl:'https://www.unicef.org/adolescentkit/reports/adolescent-kit-training-package-programme-leaders',sourceDateOrVersion:'Mayo de 2018',applicableSection:'dinámicas participativas e inclusión',reuseBasis:'ORIGINAL_SINTESIS' as const,checkedAt},
 safeguarding:{sourceTitle:'Guidelines for the Protection of Children and Vulnerable Persons',sourceAuthorOrOrg:'Santa Sede',sourceUrl:'https://www.vatican.va/resources/resources_protezioneminori-lineeguida_20190326_en.html',sourceDateOrVersion:'2019',applicableSection:'protección de menores y personas vulnerables; jurisdicción específica',reuseBasis:'ORIGINAL_SINTESIS' as const,checkedAt},
};
const seeds=[
 {id:'acogida',title:'Acogida con respeto',purpose:'Diseñar un encuentro en el que nadie sea presionado a revelar su historia.',ages:'12–18 años',group:'6–24 personas',adults:'Mínimo dos adultos responsables visibles, según normas de la organización.',roles:'Un adulto coordina y otro supervisa accesibilidad; jóvenes eligen cómo presentarse y ayudan a organizar turnos.',materials:'Tarjetas con nombres opcionales; salón accesible.',steps:['Dar bienvenida e indicar que participar o pasar es válido.','Formar grupos pequeños; proponer afinidades cotidianas no sensibles.','Recoger necesidades generales sin nombres y agradecer las contribuciones.'],adaptation:'Para 12–14 usar tarjetas; para mayores, facilitar diálogo libre; ofrecer lectura/escritura o voz.',facilitation:'Evitar interrupciones, bromas sobre identidad y contacto físico obligado.',prayer:'Jesús, ayúdanos a recibir a cada persona con dignidad.',christ:'Leer la acogida de Jesús como invitación al amor activo, sin presentar equivalencias automáticas.',biblical:{book:'Marcos',chapter:10,start:13,end:16,reason:'Jesús recibe a quienes otros querían apartar; incluir el contexto inmediato.'},safeguarding:'No pedir teléfonos, fotografías ni relatos íntimos; cumplir normativa local de menores.',sources:[sources.youth,sources.participation,sources.safeguarding]},
 {id:'amor',title:'Amor de Dios y Jesucristo',purpose:'Relacionar el mensaje cristiano de amor con decisiones respetuosas.',ages:'13–20 años',group:'4–20 personas',adults:'Dos adultos responsables presentes, uno para facilitar dudas.',roles:'Líder contextualiza el pasaje; jóvenes formulan preguntas; cofacilitador observa inclusividad.',materials:'RV1909 local, notas individuales.',steps:['Leer en voz alta el pasaje sin aislar una frase.','Pedir observaciones sobre las palabras y su destinatario.','Elegir libremente una acción de cuidado concreto.'],adaptation:'Permitir respuestas privadas; separar observación textual de aplicación; lectura asistida.',facilitation:'No usar el amor divino para exigir tolerar violencia o culpa.',prayer:'Jesucristo, que nuestras acciones reflejen cuidado y verdad.',christ:'Distinguir la enseñanza cristiana sobre amor de recomendaciones psicológicas.',biblical:{book:'Juan',chapter:15,start:9,end:17,reason:'Amor mutuo dentro del discurso de despedida; no usar como orden de sumisión a daño.'},safeguarding:'Escuchar sin diagnosticar; derivar cualquier situación de riesgo al protocolo competente.',sources:[sources.youth,sources.safeguarding]},
 {id:'liderazgo',title:'Liderazgo juvenil compartido',purpose:'Asignar tareas concretas a jóvenes con voz real y sin reemplazar supervisión adulta.',ages:'14–21 años',group:'8–30 personas',adults:'Dos adultos, con responsabilidades y protocolos formales.',roles:'Jóvenes proponen, diseñan y evalúan; adultos acompañan, resuelven permisos y seguridad.',materials:'Pizarra de tareas, recursos disponibles.',steps:['Presentar una meta realista y límites de tiempo.','Distribuir tareas elegidas voluntariamente por capacidad e interés.','Definir cómo pedir ayuda, verificar permisos y evaluar sin exponer a nadie.'],adaptation:'Rotar roles; proveer alternativas sin hablar en público.',facilitation:'Aceptar desacuerdos y repartir visibilidad.',prayer:'Danos humildad para servir y escuchar.',christ:'El modelo de servicio se diferencia del control sobre compañeros.',biblical:{book:'Marcos',chapter:10,start:35,end:45,reason:'Jesús cuestiona la búsqueda de puestos de prestigio.'},safeguarding:'Adultos conservan deber de cuidado y autorizaciones; no delegar entrevistas individuales a menores.',sources:[sources.youth,sources.participation,sources.safeguarding]},
 {id:'proteccion',title:'Protección y consentimiento',purpose:'Prevenir riesgos y conocer los límites de una reunión pastoral.',ages:'12–21 años',group:'4–30 personas',adults:'Mínimo dos adultos acreditados; aplicar proporción exigida localmente.',roles:'Responsables verifican espacios y protocolos; jóvenes conocen canales para pedir ayuda.',materials:'Contacto institucional oficial y protocolo local vigente.',steps:['Explicar reglas de respeto, privacidad y contacto físico.','Presentar canales formales de denuncia y pedir consentimiento para actividades.','Revisar accesos, salidas y acompañamiento sin aislar a ningún menor.'],adaptation:'Usar formatos visuales y orales; canal confidencial adecuado a edad.',facilitation:'No prometer confidencialidad absoluta ante riesgo inmediato.',prayer:'Que nuestro cuidado proteja la dignidad de todos.',christ:'La dignidad de cada persona guía el encuentro; no legitima ocultar daños.',biblical:{book:'Mateo',chapter:18,start:1,end:6,reason:'Discusión sobre pequeños y responsabilidad; su interpretación no sustituye normas de protección.'},safeguarding:'Este resumen NO reemplaza protocolo local, personal formado ni obligación legal de informar.',sources:[sources.safeguarding,sources.participation]},
 {id:'oracion',title:'Oración voluntaria y contexto bíblico',purpose:'Invitar a un momento de oración sin presión o evaluación espiritual.',ages:'12–21 años',group:'3–30 personas',adults:'Dos facilitadores adultos en actividades con menores.',roles:'Líder lee el contexto, cofacilitador habilita alternativas; participantes pueden guardar silencio.',materials:'RV1909 local; espacio accesible.',steps:['Presentar el tema y declarar voluntaria la participación.','Leer el texto completo del apartado seleccionado.','Ofrecer una pregunta abierta y una oración sugerida, sin pedir testimonios.'],adaptation:'Silencio, lectura escrita, pictogramas o voz; opción de permanecer sentado.',facilitation:'No evaluar a otros según sus emociones o asistencia.',prayer:'Danos atención, sabiduría y respeto en esta reunión.',christ:'La oración enseñada por Jesús se presenta sin promesas de resultados mecánicos.',biblical:{book:'Mateo',chapter:6,start:5,end:15,reason:'Instrucciones sobre motivación y oración en contexto del sermón.'},safeguarding:'Nunca forzar confesiones, contacto físico ni supervisión uno a uno.',sources:[sources.youth,sources.safeguarding]},
 {id:'inclusion',title:'Inclusión y accesibilidad',purpose:'Reducir barreras sensoriales, motrices, económicas y comunicativas.',ages:'12–21 años',group:'5–25 personas',adults:'Dos responsables, uno enfocado en accesibilidad.',roles:'Jóvenes eligen modo de participación; adulto confirma accesos y materiales adaptables.',materials:'Texto ampliado, espacio sin obstáculos y alternativa escrita.',steps:['Preguntar necesidades operativas de forma privada y opcional.','Ofrecer tareas que puedan realizarse sentado, por voz o por escrito.','Revisar barreras materiales y recibir retroalimentación sin señalar a nadie.'],adaptation:'No presumir habilidad, diagnóstico o recursos de un participante.',facilitation:'Permitir tiempo adicional y lenguaje claro.',prayer:'Enséñanos a hacer espacio para todos.',christ:'La convivencia abierta se inspira en prácticas de acogida, sin adjudicar diagnósticos al texto.',biblical:{book:'Romanos',chapter:12,start:4,end:13,reason:'Imagen de la comunidad con diversos dones; leer el capítulo.'},safeguarding:'No recopilar datos médicos ni divulgar adaptaciones individuales.',sources:[sources.participation,sources.youth]},
 {id:'servicio',title:'Servicio comunitario responsable',purpose:'Organizar una acción pequeña y consultada sin prometer soluciones universales.',ages:'14–21 años',group:'6–30 personas',adults:'Dos responsables de evaluación y permisos.',roles:'Jóvenes eligen acciones; adultos verifican autorización, riesgos y proveedores.',materials:'Lista de tareas, contactos institucionales autorizados.',steps:['Escuchar a la comunidad antes de definir necesidades.','Priorizar una acción segura con consentimiento y tareas realistas.','Evaluar con la comunidad sin publicar fotografías o datos sin permiso.'],adaptation:'Ofrecer acciones remotas o sentadas y sin gastos obligatorios.',facilitation:'Evitar hacer del servicio una competición.',prayer:'Que nuestro servicio escuche y cuide.',christ:'Jesús presenta el servicio como contrapunto a buscar prestigio.',biblical:{book:'Marcos',chapter:10,start:42,end:45,reason:'Contraste entre dominio y servicio en el camino hacia Jerusalén.'},safeguarding:'No pedir fondos o datos personales sin autorización institucional.',sources:[sources.youth,sources.participation,sources.safeguarding]},
 {id:'conflictos',title:'Desacuerdos y reparación',purpose:'Dialogar sobre desacuerdos cotidianos sin imponer reconciliación insegura.',ages:'13–21 años',group:'6–20 personas',adults:'Dos adultos, con derivación institucional si existe riesgo.',roles:'Líder modera tiempos; cofacilitador ofrece opción de retirarse; jóvenes acuerdan turnos.',materials:'Reglas de diálogo escritas.',steps:['Presentar un conflicto ficticio no violento.','Escuchar perspectivas y separar hechos, opiniones y necesidades.','Explorar acuerdos voluntarios y canales de ayuda para riesgos reales.'],adaptation:'Respuestas anónimas o escritas; no dramatizar vivencias de participantes.',facilitation:'No forzar perdón público ni mediación ante abuso.',prayer:'Danos paciencia para hablar con justicia.',christ:'La exhortación al diálogo se interpreta con cuidado y límites.',biblical:{book:'Mateo',chapter:18,start:15,end:20,reason:'Pasaje sobre conflictos comunitarios que no sustituye protocolos de abuso.'},safeguarding:'Ante violencia o protección de menores, priorizar medidas y profesionales, no dinámicas grupales.',sources:[sources.youth,sources.safeguarding]}
];
export const pastoralTopics:readonly PastoralTopic[]=seeds;
