/** R1.3 P3: Original facilitator notes for live, in-person pastoral activities.
 * No embedded game, copyrighted media or claims of reviewed doctrine.
 */
export type ActivityCategory='Conocer al grupo'|'Colaboración'|'Biblia en diálogo'|'Reflexión'|'Servicio';
export interface ActivityGuide {
 id:string;title:string;category:ActivityCategory;minutes:number;
 groupSize:string;materials:string;goal:string;
 steps:readonly [string,string,string];debrief:string;safety:string;
}
export const activityGuides:readonly ActivityGuide[]=[
 {id:'ronda-nombres',title:'Ronda de nombres y gestos',category:'Conocer al grupo',minutes:10,groupSize:'5–20',materials:'Ninguno',goal:'Aprender nombres sin exponer historias personales.',steps:['Cada persona dice su nombre y elige un gesto simple.','El siguiente repite el gesto anterior y presenta el suyo.','Cierra con una vuelta donde todos puedan pasar si lo desean.'],debrief:'¿Qué ayudó a recordar a los demás?',safety:'No exigir participación ni contacto físico.'},
 {id:'puntos-comunes',title:'Tres puntos en común',category:'Conocer al grupo',minutes:12,groupSize:'6–24',materials:'Papel opcional',goal:'Encontrar afinidades sin presuponer experiencias.',steps:['Formar grupos de tres o cuatro.','Dialogar y hallar tres gustos o intereses compartidos.','Compartir uno con el grupo grande.'],debrief:'¿Qué nos sorprendió de las coincidencias?',safety:'No preguntar por ingresos, relaciones o experiencias íntimas.'},
 {id:'mapa-esperanza',title:'Mapa de esperanzas',category:'Reflexión',minutes:15,groupSize:'4–25',materials:'Tarjetas y marcadores',goal:'Dar espacio a metas concretas y posibles.',steps:['Ofrecer escribir una meta anónima para la comunidad.','Agrupar tarjetas por temas sin atribuir autores.','Elegir juntos una acción pequeña que dependa del grupo.'],debrief:'¿Qué podemos hacer esta semana?',safety:'No pedir revelar angustias, trauma ni información identificable.'},
 {id:'puente-papel',title:'Un puente con papel',category:'Colaboración',minutes:18,groupSize:'6–30',materials:'Papel y cinta',goal:'Practicar escucha y planificación.',steps:['Formar equipos y entregar materiales iguales.','Construir un puente de papel que sostenga un objeto ligero.','Probar estructuras y comentar decisiones sin competir por personas.'],debrief:'¿Qué cambió cuando escuchamos propuestas distintas?',safety:'Evitar objetos pesados y exclusiones por habilidad motora.'},
 {id:'historias-en-cadena',title:'Historia en cadena',category:'Colaboración',minutes:12,groupSize:'5–25',materials:'Ninguno',goal:'Crear una historia colectiva con turnos.',steps:['Proponer una escena neutral de ayuda comunitaria.','Cada persona añade una frase o dice paso.','Cerrar con tres posibles finales y elegir uno juntos.'],debrief:'¿Cómo cambió la historia al sumar otras voces?',safety:'No narrar intimidad ajena ni convertir experiencias dolorosas en juego.'},
 {id:'palabras-que-cuidan',title:'Palabras que cuidan',category:'Reflexión',minutes:15,groupSize:'4–20',materials:'Tarjetas',goal:'Reconocer lenguaje de acogida.',steps:['Escribir frases breves que den bienvenida.','En parejas elegir cuáles acompañan mejor sin juzgar.','Crear un cartel colectivo con lenguaje inclusivo.'],debrief:'¿Qué palabras nos hacen sentir escuchados?',safety:'Evitar corregir testimonios personales en público.'},
 {id:'barrio-acciones',title:'Mapa de acciones del barrio',category:'Servicio',minutes:25,groupSize:'5–25',materials:'Papel grande y lápices',goal:'Proponer servicio viable sin promesas irreales.',steps:['Anotar recursos comunitarios existentes conocidos por el grupo.','Identificar una necesidad que pueda abordarse con consentimiento.','Acordar responsables y verificar antes de publicar o contactar.'],debrief:'¿A quién debemos escuchar antes de actuar?',safety:'No compartir direcciones privadas ni recopilar datos de terceros.'},
 {id:'lectura-tres-preguntas',title:'Lectura con tres preguntas',category:'Biblia en diálogo',minutes:20,groupSize:'3–20',materials:'Biblia RV1909 local',goal:'Leer un texto en contexto sin imponer interpretaciones.',steps:['Elegir en grupo un pasaje completo y leerlo despacio.','Cada persona observa qué dice, qué no dice y qué pregunta despierta.','Distinguir observaciones del texto de aplicaciones personales.'],debrief:'¿Qué necesitaríamos estudiar antes de enseñar este pasaje?',safety:'La interpretación es propuesta para diálogo, no validación pastoral humana.'},
 {id:'escucha-dos-minutos',title:'Escucha de dos minutos',category:'Conocer al grupo',minutes:12,groupSize:'4–24',materials:'Reloj',goal:'Escuchar sin interrumpir.',steps:['En parejas, elegir un tema cotidiano y neutral.','Una persona habla dos minutos; la otra escucha sin aconsejar.','Cambiar roles y agradecer sin repetir lo oído al grupo.'],debrief:'¿Qué diferencia hay entre oír y escuchar?',safety:'No usar relatos sensibles ni grabar conversaciones.'},
 {id:'camino-acuerdos',title:'Camino de acuerdos',category:'Colaboración',minutes:20,groupSize:'6–30',materials:'Papelógrafo',goal:'Practicar deliberación respetuosa.',steps:['Plantear una decisión simulada de organización de evento.','Cada equipo explica opciones con ventajas y riesgos.','Consensuar un criterio y decidir cómo revisar el acuerdo.'],debrief:'¿Qué hicimos cuando surgieron diferencias?',safety:'Ningún participante debe revelar convicciones íntimas.'},
 {id:'gratitud-objetos',title:'Objetos de gratitud',category:'Reflexión',minutes:12,groupSize:'4–20',materials:'Objetos cotidianos opcionales',goal:'Expresar agradecimiento libremente.',steps:['Presentar un objeto cotidiano o una palabra.','Explicar una razón sencilla para agradecer o pasar.','Terminar reconociendo el aporte del grupo.'],debrief:'¿Qué gestos de gratitud podemos practicar?',safety:'No asumir que todos atraviesan circunstancias fáciles.'},
 {id:'versiculo-contexto',title:'Versículo y contexto',category:'Biblia en diálogo',minutes:20,groupSize:'4–20',materials:'Biblia RV1909 local',goal:'Evitar interpretaciones aisladas.',steps:['Elegir una referencia y leer el capítulo cercano.','En equipos ubicar hablante, destinatario y situación textual.','Compartir una pregunta para estudio adicional.'],debrief:'¿Qué cambió al leer antes y después?',safety:'No etiquetar conclusiones como doctrina aprobada.'},
 {id:'semillas-ideas',title:'Semillas de ideas',category:'Servicio',minutes:18,groupSize:'5–30',materials:'Notas adhesivas',goal:'Convertir deseos de ayuda en propuestas concretas.',steps:['Cada persona anota una idea de apoyo comunitario.','Agrupar por recursos y accesibilidad.','Escoger un piloto pequeño que requiera pocos permisos.'],debrief:'¿Cómo evaluaremos si fue útil?',safety:'No ofrecer servicios profesionales sin calificación.'},
 {id:'cadena-agradecimiento',title:'Cadena de agradecimiento',category:'Conocer al grupo',minutes:10,groupSize:'5–25',materials:'Ninguno',goal:'Visibilizar aportes observables.',steps:['Nombrar una acción colaborativa que se haya visto hoy.','Agradecer sin evaluar rasgos personales.','Permitir silencios y cerrar reconociendo el esfuerzo conjunto.'],debrief:'¿Qué gestos nos animaron a participar?',safety:'Evitar favoritismos y elogios de apariencia.'},
 {id:'equipo-sin-palabras',title:'Equipo sin palabras',category:'Colaboración',minutes:15,groupSize:'6–20',materials:'Fichas de figuras',goal:'Explorar comunicación no verbal accesible.',steps:['Cada equipo recibe piezas para ordenar una secuencia.','Resolver primero con señas voluntarias y apoyo escrito.','Comparar cómo se coordinó el equipo.'],debrief:'¿Qué barreras hubo y cómo las reducimos?',safety:'Adaptar con texto/audio; no excluir por sordera, visión o movilidad.'},
 {id:'parabolas-preguntas',title:'Preguntas ante una parábola',category:'Biblia en diálogo',minutes:22,groupSize:'4–20',materials:'Texto bíblico',goal:'Distinguir relato, audiencia y aplicación.',steps:['Elegir una parábola y leer el contexto narrativo.','Formular preguntas de observación sin debatir quién tiene razón.','Proponer investigación pastoral posterior si hay desacuerdos.'],debrief:'¿Qué información falta para comprender mejor el relato?',safety:'No atribuir a Dios afirmaciones del grupo sin revisión contextual.'},
 {id:'red-servicio',title:'Red de servicio',category:'Servicio',minutes:20,groupSize:'5–25',materials:'Pizarra',goal:'Conectar capacidades disponibles con tareas prudentes.',steps:['Listar tareas de un evento hipotético.','Distribuirlas por disponibilidad voluntaria.','Nombrar apoyo alternativo y verificar consentimientos.'],debrief:'¿A quién dejamos fuera sin querer?',safety:'No registrar teléfonos personales ni horarios privados en público.'},
 {id:'pausa-observacion',title:'Pausa de observación',category:'Reflexión',minutes:12,groupSize:'3–25',materials:'Papel',goal:'Atender a lo que ocurre antes de reaccionar.',steps:['Invitar a observar un espacio tranquilo por un minuto.','Anotar algo oído o visto sin evaluarlo.','Compartir cómo cambiaron las observaciones al escuchar a otros.'],debrief:'¿Qué solemos pasar por alto?',safety:'Alternativa sentada o con ojos abiertos; no imponer ejercicios corporales.'},
 {id:'tarea-compartida',title:'Tarea compartida',category:'Colaboración',minutes:15,groupSize:'6–30',materials:'Papel y marcadores',goal:'Repartir responsabilidades con equidad.',steps:['Plantear la preparación de una reunión ficticia.','Asignar tareas considerando fortalezas y accesibilidad.','Revisar qué quedó sin cubrir y ajustar juntos.'],debrief:'¿Qué significa colaborar sin sobrecargar?',safety:'Evitar presión para asumir voluntariados reales.'},
 {id:'proximo-paso',title:'Un próximo paso',category:'Servicio',minutes:15,groupSize:'3–30',materials:'Tarjetas',goal:'Cerrar con compromisos pequeños y opcionales.',steps:['Cada persona elige una acción solidaria realista o dice paso.','En pequeños grupos identificar obstáculos generales.','Acordar fecha para evaluar, sin vigilar decisiones individuales.'],debrief:'¿Cómo acompañar sin controlar?',safety:'No pedir pruebas de cumplimiento ni datos sensibles.'},
];
export const activityCategories=[...new Set(activityGuides.map(x=>x.category))] as readonly ActivityCategory[];
