export interface TopicDefinition { id:string; label:string; family:string; aliases:readonly string[]; relatedTerms:readonly string[]; version:'m1-v1'; }
const rows: readonly [string,string,string,readonly string[],readonly string[]][] = [
  ["dios","Dios","Dios y fe",["Señor", "Jehová"],[]],
  ["jesus","Jesús","Dios y fe",["Cristo", "Jesucristo"],[]],
  ["espiritu-santo","Espíritu Santo","Dios y fe",["Espíritu de Dios"],[]],
  ["fe","fe","Dios y fe",["creer", "creyó", "creyeron"],["confianza", "creer"]],
  ["confianza","confianza","Dios y fe",["confiar", "confió"],[]],
  ["gracia","gracia","Dios y fe",["favor"],["misericordia", "salvación"]],
  ["salvacion","salvación","Dios y fe",["salvar", "salvó", "salvos"],["redención", "vida eterna"]],
  ["evangelio","evangelio","Dios y fe",["buenas nuevas"],["Cristo", "salvación"]],
  ["reino-de-dios","reino de Dios","Dios y fe",["reino de los cielos"],["reino", "justicia"]],
  ["voluntad-de-dios","voluntad de Dios","Dios y fe",["voluntad del Señor"],["obediencia", "mandamientos"]],
  ["amor","amor","Amor y relaciones",["amar", "amó", "amados"],["caridad", "prójimo"]],
  ["amistad","amistad","Amor y relaciones",["amigo", "amigos"],[]],
  ["familia","familia","Amor y relaciones",["casa", "hogar"],[]],
  ["matrimonio","matrimonio","Amor y relaciones",["marido", "mujer", "esposo", "esposa"],[]],
  ["hijos","hijos","Amor y relaciones",["hijo", "hija", "hijas"],[]],
  ["projimo","prójimo","Amor y relaciones",["prójimos"],[]],
  ["comunidad","comunidad","Amor y relaciones",["hermanos", "congregación"],[]],
  ["unidad","unidad","Amor y relaciones",["unánimes", "uno"],[]],
  ["reconciliacion","reconciliación","Amor y relaciones",["reconciliar", "reconciliados"],["paz", "perdón"]],
  ["servicio","servicio","Amor y relaciones",["servir", "siervo"],["siervo", "prójimo"]],
  ["perdon","perdón","Perdón y restauración",["perdonar", "perdonó", "perdonados"],["misericordia", "reconciliación"]],
  ["misericordia","misericordia","Perdón y restauración",["misericordioso", "compadecer"],["compasión", "perdón"]],
  ["arrepentimiento","arrepentimiento","Perdón y restauración",["arrepentíos", "arrepentirse"],["confesión", "perdón"]],
  ["pecado","pecado","Perdón y restauración",["pecados", "pecar"],["iniquidad", "transgresión"]],
  ["tentacion","tentación","Perdón y restauración",["tentado", "tentar"],[]],
  ["culpa","culpa","Perdón y restauración",["culpable", "iniquidad"],[]],
  ["restauracion","restauración","Perdón y restauración",["restaurar", "restituir"],[]],
  ["confesion","confesión","Perdón y restauración",["confesar", "confesamos"],[]],
  ["obediencia","obediencia","Perdón y restauración",["obedecer", "obedeció"],[]],
  ["santidad","santidad","Perdón y restauración",["santo", "santos"],["obediencia", "santo"]],
  ["paz","paz","Vida interior",["pacificar"],["reconciliación", "reposo"]],
  ["esperanza","esperanza","Vida interior",["esperar"],["promesa", "esperar"]],
  ["gozo","gozo","Vida interior",["gozar", "alegría"],["alegría", "regocijo"]],
  ["gratitud","gratitud","Vida interior",["agradecer"],["acción de gracias", "alabanza"]],
  ["paciencia","paciencia","Vida interior",["paciente", "esperar"],[]],
  ["humildad","humildad","Vida interior",["humilde"],["mansedumbre", "servicio"]],
  ["sabiduria","sabiduría","Vida interior",["sabio", "sabios"],["entendimiento", "prudencia"]],
  ["valentia","valentía","Vida interior",["valiente", "esfuerzo"],[]],
  ["contentamiento","contentamiento","Vida interior",["contento"],[]],
  ["dominio-propio","dominio propio","Vida interior",["templanza"],["templanza", "disciplina"]],
  ["miedo","miedo","Dificultades y emociones",["temor", "temer"],["temor", "confianza"]],
  ["ansiedad","ansiedad","Dificultades y emociones",["afán", "afanes"],["afán", "preocupación"]],
  ["tristeza","tristeza","Dificultades y emociones",["triste", "llorar"],[]],
  ["soledad","soledad","Dificultades y emociones",["solo", "desamparado"],[]],
  ["enojo","enojo","Dificultades y emociones",["ira", "airarse"],[]],
  ["sufrimiento","sufrimiento","Dificultades y emociones",["padecer", "aflicción"],["aflicción", "paciencia"]],
  ["duelo","duelo","Dificultades y emociones",["luto", "lloro"],["consuelo", "lloro"]],
  ["desanimo","desánimo","Dificultades y emociones",["desmayar", "desfallecer"],[]],
  ["preocupacion","preocupación","Dificultades y emociones",["afán", "cuidado"],[]],
  ["cansancio","cansancio","Dificultades y emociones",["cansado", "fatiga"],[]],
  ["oracion","oración","Oración y práctica espiritual",["orar", "orad"],["petición", "intercesión"]],
  ["alabanza","alabanza","Oración y práctica espiritual",["alabar", "alabad"],["adoración", "acción de gracias"]],
  ["adoracion","adoración","Oración y práctica espiritual",["adorar", "adorad"],["alabanza", "Dios"]],
  ["ayuno","ayuno","Oración y práctica espiritual",["ayunar", "ayunó"],[]],
  ["meditacion","meditación","Oración y práctica espiritual",["meditar"],["palabra", "ley"]],
  ["lectura-biblica","lectura bíblica","Oración y práctica espiritual",["Escritura", "Escrituras"],["Escrituras", "palabra"]],
  ["escucha","escucha","Oración y práctica espiritual",["oír", "oye"],[]],
  ["peticion","petición","Oración y práctica espiritual",["pedir", "pedid"],[]],
  ["intercesion","intercesión","Oración y práctica espiritual",["interceder", "ruego"],[]],
  ["accion-de-gracias","acción de gracias","Oración y práctica espiritual",["gracias", "agradecimiento"],[]],
  ["honestidad","honestidad","Carácter y conducta",["verdad", "íntegro"],[]],
  ["generosidad","generosidad","Carácter y conducta",["generoso", "dar"],[]],
  ["justicia","justicia","Carácter y conducta",["justo", "justos"],["juicio", "justo"]],
  ["compasion","compasión","Carácter y conducta",["compasivo", "compadecer"],["misericordia", "prójimo"]],
  ["bondad","bondad","Carácter y conducta",["bueno", "benignidad"],["amor", "misericordia"]],
  ["fidelidad","fidelidad","Carácter y conducta",["fiel", "fieles"],["fe", "fiel"]],
  ["responsabilidad","responsabilidad","Carácter y conducta",["mayordomo", "encargo"],[]],
  ["trabajo","trabajo","Carácter y conducta",["trabajar", "obra"],[]],
  ["descanso","descanso","Carácter y conducta",["reposo", "descansar"],[]],
  ["disciplina","disciplina","Carácter y conducta",["corrección", "disciplinar"],[]],
  ["decisiones","decisiones","Decisiones y vida cotidiana",["escoger", "elegir"],[]],
  ["proposito","propósito","Decisiones y vida cotidiana",["propósitos", "designio"],[]],
  ["direccion","dirección","Decisiones y vida cotidiana",["guiar", "camino"],["sabiduría", "camino"]],
  ["dinero","dinero","Decisiones y vida cotidiana",["riquezas", "tesoro"],["riquezas", "generosidad"]],
  ["trabajo-y-vocacion","trabajo y vocación","Decisiones y vida cotidiana",["obra", "oficio"],[]],
  ["estudios","estudios","Decisiones y vida cotidiana",["aprender", "enseñar"],[]],
  ["tiempo","tiempo","Decisiones y vida cotidiana",["días", "hora"],[]],
  ["salud","salud","Decisiones y vida cotidiana",["sanar", "sanidad"],["sanar", "enfermedad"]],
  ["sexualidad","sexualidad","Decisiones y vida cotidiana",["fornicación", "adulterio"],[]],
  ["conflictos","conflictos","Decisiones y vida cotidiana",["contienda", "pleito"],["paz", "reconciliación"]],
  ["creacion","creación","Biblia y comprensión",["crear", "creó"],["Dios", "crear"]],
  ["pacto","pacto","Biblia y comprensión",["alianza", "pactó"],["promesa", "ley"]],
  ["ley","ley","Biblia y comprensión",["mandato", "estatutos"],[]],
  ["profecia","profecía","Biblia y comprensión",["profeta", "profetizar"],["profeta", "promesa"]],
  ["parabolas","parábolas","Biblia y comprensión",["parábola"],[]],
  ["milagros","milagros","Biblia y comprensión",["señales", "maravillas"],[]],
  ["resurreccion","resurrección","Biblia y comprensión",["resucitar", "resucitó"],["vida", "Jesús"]],
  ["cruz","cruz","Biblia y comprensión",["crucificar", "crucificado"],["Cristo", "salvación"]],
  ["mandamientos","mandamientos","Biblia y comprensión",["mandamiento", "mandó"],[]],
  ["promesas","promesas","Biblia y comprensión",["promesa", "prometió"],["pacto", "esperanza"]],
  ["vida-eterna","vida eterna","Esperanza y vida cristiana",["vida perpetua"],["salvación", "resurrección"]],
  ["muerte","muerte","Esperanza y vida cristiana",["morir", "muerto"],["resurrección", "vida"]],
  ["juicio","juicio","Esperanza y vida cristiana",["juzgar", "juez"],["justicia", "juez"]],
  ["cielo","cielo","Esperanza y vida cristiana",["cielos"],[]],
  ["mision","misión","Esperanza y vida cristiana",["enviar", "enviados"],["evangelio", "enviar"]],
  ["discipulado","discipulado","Esperanza y vida cristiana",["discípulo", "discípulos"],["discípulo", "seguir"]],
  ["testimonio","testimonio","Esperanza y vida cristiana",["testigo", "testigos"],["testigo", "evangelio"]],
  ["iglesia","iglesia","Esperanza y vida cristiana",["iglesias", "congregación"],["comunidad", "hermanos"]],
  ["dones","dones","Esperanza y vida cristiana",["don", "ministerios"],["servicio", "Espíritu"]],
  ["fruto-del-espiritu","fruto del Espíritu","Esperanza y vida cristiana",["fruto", "Espíritu"],["amor", "gozo", "paz"]],
];
export const topicCatalog: readonly TopicDefinition[] = rows.map(([id,label,family,aliases,relatedTerms])=>({id,label,family,aliases,relatedTerms,version:'m1-v1'}));
export function normalizeTopicText(value:string){return value.trim().toLocaleLowerCase('es').normalize('NFD').replace(/[\u0300-\u036f]/g,'');}
const topicIndex=new Map<string,TopicDefinition>();
for(const topic of topicCatalog){for(const key of [topic.id,topic.label,...topic.aliases]) topicIndex.set(normalizeTopicText(key),topic);}
export function resolveTopic(value:string):TopicDefinition|undefined{return topicIndex.get(normalizeTopicText(value));}
export function isTopic(value:string){return resolveTopic(value)!==undefined;}
