import { useEffect, useMemo, useState } from 'react';
import { ScrollView, StyleSheet } from 'react-native';
import { useSQLiteContext } from 'expo-sqlite';
import { SQLiteLocalPersistence } from '../../db/sqliteLocalPersistence';
import { defaultPreferences, onboardingSteps, type LocalPreferences } from '../../product/preferences';
import type { Theme } from '../theme';
import { spacing } from '../theme';
import { Action, Body, Card, Heading, Screen } from '../primitives';

export function SettingsScreen({theme,onPreferencesChange}:{theme:Theme;onPreferencesChange?:(value:LocalPreferences)=>void}){
  const db=useSQLiteContext(); const persistence=useMemo(()=>new SQLiteLocalPersistence(db),[db]);
  const [prefs,setPrefs]=useState(defaultPreferences); const [status,setStatus]=useState('Cargando preferencias locales…');
  useEffect(()=>{let active=true;void persistence.getPreferences().then(value=>{if(active){setPrefs(value);onPreferencesChange?.(value);setStatus('');}}).catch(()=>{if(active)setStatus('No se pudieron leer las preferencias locales.');});return()=>{active=false};},[persistence,onPreferencesChange]);
  const update=async(next:LocalPreferences)=>{setPrefs(next);onPreferencesChange?.(next);try{await persistence.setPreferences(next);setStatus('Preferencias guardadas en este dispositivo.');}catch{setStatus('No se pudieron guardar las preferencias locales.');}};
  return <Screen theme={theme}><ScrollView contentContainerStyle={styles.stack}><Heading theme={theme}>Ajustes</Heading>{status?<Body theme={theme} muted>{status}</Body>:null}<Card theme={theme}><Heading theme={theme}>Lectura</Heading><Body theme={theme}>Tamaño: {Math.round(prefs.fontScale*100)}%</Body><Action label="Aumentar texto" secondary theme={theme} onPress={()=>void update({...prefs,fontScale:Math.min(1.6,prefs.fontScale+.1)})}/><Action label="Reducir texto" secondary theme={theme} onPress={()=>void update({...prefs,fontScale:Math.max(.8,prefs.fontScale-.1)})}/><Action label="Restablecer tamaño" secondary theme={theme} onPress={()=>void update({...prefs,fontScale:1})}/><Action label={`Tema: ${prefs.theme}`} secondary theme={theme} onPress={()=>void update({...prefs,theme:prefs.theme==='system'?'light':prefs.theme==='light'?'dark':'system'})}/></Card><Card theme={theme}><Heading theme={theme}>Introducción</Heading><Body theme={theme} muted>{onboardingSteps.map(step=>step.title).join(' · ')}</Body><Body theme={theme}>{prefs.onboardingComplete?'Completada':'Pendiente'}</Body><Action label={prefs.onboardingComplete?'Reiniciar introducción':'Marcar introducción completada'} secondary theme={theme} onPress={()=>void update({...prefs,onboardingComplete:!prefs.onboardingComplete})}/></Card><Card theme={theme}><Heading theme={theme}>Recordatorio</Heading><Body theme={theme}>{prefs.reminderEnabled?`Preferencia activa · ${prefs.reminderTime}`:'Desactivado'}</Body><Action label={prefs.reminderEnabled?'Desactivar preferencia':'Activar preferencia de las 08:00'} theme={theme} onPress={()=>void update({...prefs,reminderEnabled:!prefs.reminderEnabled})}/><Body theme={theme} muted>Esta versión guarda la preferencia localmente; no promete una alarma del sistema ni una entrega exacta.</Body></Card><Card theme={theme}><Heading theme={theme}>Privacidad y fuente</Heading><Body theme={theme}>Sin cuenta obligatoria. Preferencias y datos de uso permanecen locales.</Body><Body theme={theme} muted>Reina-Valera 1909 · fuente BibleAquifer · dominio público/CC0 del paquete.</Body></Card></ScrollView></Screen>;
}
const styles=StyleSheet.create({stack:{gap:spacing.lg,paddingBottom:spacing.xxl}});
