import { describe,expect,it,vi } from 'vitest'; import { SQLiteBibleRepository } from './sqliteBibleRepository';
describe('SQLiteBibleRepository',()=>{it('maps bundled chapter rows',async()=>{const getAllAsync=vi.fn().mockResolvedValue([{bookId:'John',bookName:'Juan',chapter:3,verse:16,sourceVerseLabel:'16',text:'texto RV1909'}]);const r=new SQLiteBibleRepository({getAllAsync} as never);await expect(r.getChapter('Juan',3)).resolves.toHaveLength(1);});it('does not query invalid chapters',async()=>{const getAllAsync=vi.fn();const r=new SQLiteBibleRepository({getAllAsync} as never);await expect(r.getChapter('John',0)).resolves.toEqual([]);expect(getAllAsync).not.toHaveBeenCalled();});it('keeps literal hits explicitly literal',async()=>{const getAllAsync=vi.fn().mockResolvedValue([{bookId:'John',bookName:'Juan',chapter:3,verse:16,sourceVerseLabel:'16',text:'Porque de tal manera amó Dios...'}]);const r=new SQLiteBibleRepository({getAllAsync} as never);const hits=await r.searchLiteral('"amó Dios"',10);expect(hits[0]).toMatchObject({matchType:'literal_exact',translationId:'rv1909'});expect(hits[0].explanation).toContain('Coincidencia literal');});it('escapes LIKE wildcards and ignores blank literal queries',async()=>{const getAllAsync=vi.fn().mockResolvedValue([]);const r=new SQLiteBibleRepository({getAllAsync} as never);await r.searchLiteral('   ');expect(getAllAsync).not.toHaveBeenCalled();await r.searchLiteral('100%_');expect(getAllAsync.mock.calls[0][2]).toBe('100\\%\\_');});it('accepts whole curated lexical forms with deterministic explanation',async()=>{const getAllAsync=vi.fn().mockResolvedValue([{bookId:'John',bookName:'Juan',chapter:3,verse:16,sourceVerseLabel:'16',text:'Porque de tal manera amó Dios...'}]);const r=new SQLiteBibleRepository({getAllAsync} as never);const hits=await r.searchTopic('amor');expect(hits[0]).toMatchObject({matchType:'lexical_related_form',translationId:'rv1909'});expect(hits[0].explanation).toContain('forma completa “amó”');});it('rejects unrelated substring hits such as llamó for amor',async()=>{const getAllAsync=vi.fn().mockResolvedValue([{bookId:'Gen',bookName:'Génesis',chapter:1,verse:5,sourceVerseLabel:'5',text:'Y llamó Dios a la luz Día...'}]);const r=new SQLiteBibleRepository({getAllAsync} as never);await expect(r.searchTopic('amor')).resolves.toEqual([]);});it('marks whole thematic terms separately from lexical forms',async()=>{const getAllAsync=vi.fn().mockResolvedValue([{bookId:'Luke',bookName:'Lucas',chapter:10,verse:27,sourceVerseLabel:'27',text:'...a tu prójimo como a ti mismo'}]);const r=new SQLiteBibleRepository({getAllAsync} as never);const hits=await r.searchTopic('amor');expect(hits[0].matchType).toBe('thematic_term');expect(hits[0].explanation).toContain('temática curada');});it('returns no results for unknown topics without querying',async()=>{const getAllAsync=vi.fn();const r=new SQLiteBibleRepository({getAllAsync} as never);await expect(r.searchTopic('no-existe')).resolves.toEqual([]);expect(getAllAsync).not.toHaveBeenCalled();});});


describe('D05 book navigation metadata',()=>{it('reads chapter count from existing translation metadata without changing corpus',async()=>{const getAllAsync=vi.fn().mockResolvedValue([{chapterCount:21}]);const r=new SQLiteBibleRepository({getAllAsync} as never);await expect(r.getBookChapterCount('Juan')).resolves.toBe(21);expect(getAllAsync).toHaveBeenCalledTimes(1);});});


describe('RC02 H search-v2 literal matching',()=>{
  it('rejects substring matching inside unrelated words',async()=>{
    const db={getAllAsync:vi.fn().mockResolvedValue([{bookId:'Psa',bookName:'Salmos',chapter:1,verse:1,sourceVerseLabel:'1',text:'El enamorado llamó a otra persona'},{bookId:'Psa',bookName:'Salmos',chapter:1,verse:2,sourceVerseLabel:'2',text:'El amor es paciente'}])};
    const repo=new SQLiteBibleRepository(db as never);
    const result=await repo.searchLiteral('amor');
    expect(result.map(v=>v.sourceVerseLabel)).toEqual(['2']);
  });
  it('ranks whole-word lexical evidence ahead of thematic evidence deterministically',async()=>{
    const db={getAllAsync:vi.fn().mockResolvedValue([{bookId:'Gen',bookName:'Génesis',chapter:1,verse:1,sourceVerseLabel:'1',text:'...a tu prójimo como a ti mismo'}, {bookId:'John',bookName:'Juan',chapter:1,verse:1,sourceVerseLabel:'1',text:'Con gran amor'}])};
    const repo=new SQLiteBibleRepository(db as never);
    const hits=await repo.searchTopic('amor');
    expect(hits[0].matchType).toBe('lexical_related_form');
    expect(hits[1].matchType).toBe('thematic_term');
  });
});
